### ISSUE TITLE
Error when running in dev

### ISSUE THREAD

**Issue by voger** [authentic-pixels/ex-shop#3]
I followed the instalation instructions and I got this error

```
$ mix phoenix.server
[info] Application sentry exited: exited in: Sentry.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (RuntimeError) environment_name not configured
            (sentry) lib/sentry.ex:84: Sentry.check_required_env!/0
            (sentry) lib/sentry.ex:37: Sentry.start/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4
[info] Application uuid exited: :stopped
[info] Application quantum exited: :stopped
[info] Application bamboo exited: :stopped
[info] Application httpoison exited: :stopped
[info] Application timex exited: :stopped
[info] Application combine exited: :stopped
[info] Application tzdata exited: :stopped
[info] Application hackney exited: :stopped
[info] Application metrics exited: :stopped
[info] Application ssl_verify_fun exited: :stopped
[info] Application certifi exited: :stopped
[info] Application mimerl exited: :stopped
[info] Application idna exited: :stopped
[info] Application cloudini exited: :stopped
[info] Application quintana exited: :stopped
[info] Application folsom exited: :stopped
[info] Application bear exited: :stopped
[info] Application comeonin exited: :stopped
[info] Application postgrex exited: :stopped
[info] Application db_connection exited: :stopped
[info] Application connection exited: :stopped
[info] Application phoenix_ecto exited: :stopped
[info] Application ecto exited: :stopped
[info] Application poolboy exited: :stopped
[info] Application decimal exited: :stopped
[info] Application gettext exited: :stopped
[info] Application cowboy exited: :stopped
[info] Application cowlib exited: :stopped
[info] Application ranch exited: :stopped
[info] Application phoenix_html exited: :stopped
[info] Application phoenix_pubsub exited: :stopped

=INFO REPORT==== 19-Oct-2016::08:59:35 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application sentry: exited in: Sentry.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (RuntimeError) environment_name not configured
            (sentry) lib/sentry.ex:84: Sentry.check_required_env!/0
            (sentry) lib/sentry.ex:37: Sentry.start/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4

```

The solution was to copy this block from config/prod.exs to config/dev.exs and change the environment_name to :dev

```

config :sentry,
  use_error_logger: true,
  environment_name: :prod,
  dsn: System.get_env("SENTRY_DSN"),
  tags: %{
    env: "production"
  }
```

**Comment by bharani91** [comment]
Yes, your solution is correct. I have used the following code in my config/dev.secrets.exs file.

```
config :sentry,
  use_error_logger: false,
  environment_name: :dev,
  dsn: System.get_env("SENTRY_DSN"),
  included_environments: ~w(prod)a,
  tags: %{
    env: "development"
  }

```

I will add this to to README.
